### ISSUE TITLE
Github Actions Bot to help with maintence 

### ISSUE THREAD

**Issue by JoshuaMacklin** [flathub/io.freetubeapp.FreeTube#95]
Is there any interest in adding a github actions bot to automatically make PRs / builds on new releases? Could make maintaining the flathub repo a breeze! 

Plus with Flathubs push for more robust metadata, this could help close [the Changelog issue](https://github.com/flathub/io.freetubeapp.FreeTube/issues/92) and have it automated.

I could look into myself if no one else has experience using it.

**Comment by Alexander-Wilms** [comment]
You can use https://github.com/flathub-infra/flatpak-external-data-checker to update the manifest.

Cf. https://github.com/flathub/org.texstudio.TeXstudio/blob/c434036081b90d8284425092457dc2ab5bcba84d/org.texstudio.TeXstudio.yaml#L70-L77:

```yaml
    sources:
      - type: archive
        url: https://poppler.freedesktop.org/poppler-24.01.0.tar.xz
        sha256: c7def693a7a492830f49d497a80cc6b9c85cb57b15e9be2d2d615153b79cae08
        x-checker-data:
          type: anitya
          project-id: 3686
          url-template: https://poppler.freedesktop.org/poppler-$version.tar.xz
```

For TeXstudio, I wrote a script that adds the changelog to the matainfo:
https://github.com/flathub/org.texstudio.TeXstudio/blob/master/changelog2metainfo.sh
